name: ds200s

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies: 
  - python >= 3.8
  - pytorch
  - torchvision
  - cpuonly
  - matplotlib
  - seaborn
  - scipy
  - tqdm
  - scikit-learn
  - scikit-image
  - pandas
  - numpy
  - jupyter
  - pip:
      - opencv-python
